config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :admins

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'customers#new'

  resources :customers

  resources :admins

  resources :super_admins

  resources :records


  resources :cars do
    member do
      get 'schedule'
      post 'action'
      patch 'action'
      get 'beforecheckout'
      get 'subscribe'
     # get 'checkout'
      get 'return'
      post 'reserve'
      get 'cancel'
      get 'approve'
      get 'disapprove'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :records, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password,
            presence: true,
            length: { minimum: 6 },
            unless: :password_skip?
  def password_skip?
    @password_skip
  end

  def password_need
    @password_skip = false
  end

  def password_no_deed
    @password_skip = true
  end

  def update_charge(charge)
    update_attribute(:charge, charge)
  end

  def update_status(status)
    update_attribute(:status, status)
  end

  def update_record_id(record_id)
    update_attribute(:record_id, record_id)
  end

  def update_car_id(car_id)
    update_attribute(:car_id, car_id)
  end
  def update_subscribe_car_id(car_id)
    update_attribute(:subscribe_car_id, car_id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, except: %i[index new create]
  before_action :back_if_not_logged_in, except: %i[new create destroy]
  before_action :back_if_customer, only: %i[index new create]
  before_action :back_if_not_self_customer, only: %i[show edit update]
  # GET /customers
  # GET /customers.json
  def index
    if !logged_in?
      redirect_to login_url
    elsif current_authority == $customer
      redirect_to customer_url(current_user)
    end
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    if logged_in?
      if current_authority=="Customer"
        redirect_to customer_url(current_user)
      elsif current_authority=="Admin"
        redirect_to admin_url(current_user)
      else
        redirect_to super_admin_url(current_user)
      end
    end
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    unless Admin.find_by(email: params[:customer][:email]).nil? && SuperAdmin.find_by(email: params[:customer][:email]).nil?
      redirect_to new_customer_url
      return
    end
    @customer = Customer.new(customer_params)
    @customer.charge = 0
    @customer.status = $returned
    respond_to do |format|
      if @customer.save
        log_in @customer, $customer
        #CustomerMailer.available_email(@customer).deliver_now
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    customer_params[:email].downcase!
    @customer.password_no_deed if current_authority != $customer
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  ensure
    @customer.password_need
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    # Update status of the car relative to this customer to 'Available'.
    unless @customer.car_id.nil?
    car = Car.find_by(id: @customer.car_id)
    car.update_status($available)
    car.update_attribute(:customer_id, "")
    end
   
    unless  $scheduler.job(@customer.job_id).nil?
      $scheduler.job(@customer.job_id).unschedule
    end
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name, :email, :password, :password_confirmation, :charge, :record_id)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def pin_customer customer
    session[:customer_id] = customer.id
  end

  def current_customer
    @current_customer ||= Customer.find(session[:customer_id])
  end

  def delete_customer_pin
    session.delete(:customer_id)
    @current_customer = nil
  end
end

app/views/customers/_form.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@customer) do |f| %>
        <% if @customer.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                The form contains <%= pluralize(@customer.errors.count, 'error') %>.
              </div>
              <ul>
                <% @customer.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>
        <% if current_authority == $customer || !logged_in? %>
            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation %>
        <% end %>
        <div class="field">
        </div>
        <div class="field">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', @customer %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Customers</h2>
<br>
<table style="margin:0 auto">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Charge</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.charge %></td>
        <td><%= link_to 'Details', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>


<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<!-- <p>
  <strong>Password digest:</strong>
  <%= @customer.password_digest %>
</p>-->

<p>
  <strong>Charge:</strong>
  <%= @customer.charge %>
</p>
<% if current_authority == $customer %>
    <%= link_to 'Edit My Profile', edit_customer_path(@customer) %>
<% else %>
    <%= link_to 'Edit', edit_customer_path(@customer) %>
<% end %>

app/views/customers/showcar_customer.html.erb
<p>
  <strong>License:</strong>
  <%= @car.license %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @car.rate %>
</p>

<p>
  <strong>Style:</strong>
  <%= @car.style %>
</p>

<p>
  <strong>Location:</strong>
  <%= @car.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
<p id="notice"><%= notice %></p>
  <hr>   <hr>
</p>


<% if @customer.recordid.nil? %>
    <% if @car.status == "Available"%>
        <%= form_tag(reserve_customer_path(@car), method: "get") do %>
          <strong>Start Time:</strong>
            <%= select_datetime  Time.now, prefix: :start_date %>
          <%= "(*Within 7 days)" %>
          <br>
          <br>
          <strong>Rental Hours:</strong>
          <%= select_tag :day, options_for_select([['1', 1], ['2', 2], ['3', 3],['4', 4],['5', 5],['6', 6],['7', 7],['8', 8],['9', 9],['10',10]]) %>
          <br>
            <%= submit_tag("Reserve") %>
          <hr><hr>
        <% end %>
            <%= form_tag(checkout_customer_path([@car, @customer]), method: "get") do %>
                <strong>Rental Hours:     </strong>
                <%= select_tag :h, options_for_select([['1', 1], ['2', 2], ['3', 3],['4', 4],['5', 5],['6', 6],['7', 7],['8', 8],['9', 9],['10',10]]) %>
                <br>
                <br>
                <%= submit_tag("Rent") %>
                <hr><hr>
            <% end %>
    <% end %>
<% elsif @customer.recordid < 0 %>
            <% if @customer.recordid  == (-1 - @car.id) %>
              <%= form_tag(checkout_customer_path([@car, @customer]), method: "get") do %>
                  <strong>Rental Hours:     </strong>
                  <%= select_tag :h, options_for_select([['1', 1], ['2', 2], ['3', 3],['4', 4],['5', 5],['6', 6],['7', 7],['8', 8],['9', 9],['10',10]]) %>
                  <br>
                  <br>
                  <%= submit_tag("Rent") %>
                  <hr><hr>
             <% end %>
            <% end %>
<% else%>
    <% @record = Record.find(@customer.recordid) %>
    <% if @record.car== @car %>
    <td><%= link_to 'Return', return_customer_path(@car )%></td>
    <hr>   <hr>
    <% end %>
<% end %>
<%= link_to 'Back', search_customer_path%>